### ISSUE TITLE
output issue

### ISSUE THREAD

**Issue by Rhea1505** [RahulSurana123/competitive_coding#172]

**Comment by deveshm26** [comment]
What is the sample test case for this part?? Can you explain the code???

**Comment by RahulSurana123** [comment]
> What is the sample test case for this part?? Can you explain the code???

I don't have that now but you can read explaination on this link 
https://leetcode.com/discuss/interview-question/1279262/Juspay-Tree-of-Space-Locking-and-Unlocking-N-Ary-Tree/1274504
