### ISSUE TITLE
Help with Question

### ISSUE THREAD

**Issue by SamraatBansal** [RahulSurana123/competitive_coding#207]
Hey Rahul

Your Repository has been an amazing help to me, I am interviewing for Juspay in few days, I am looking for all the previously asked questions in interview
I stumbled upon this ' Hiring/juspay interview question.cpp ' Can you point me towards the question of this solution, also If you happen to have any more set of questions that have been asked in Juspay it would be great help

Regards
Samraat Bansal

**Comment by RahulSurana123** [comment]
Hii samraat,

The question that I was asked was on validate a binary search tree and the second one was to set a bit in a string to make it from hdllo to hello using only pointer, and no of the bytes present in string and bit no that we want to make high

I don't have any other questions with me right now but if you are good with medium level leetcode question then you will easily be able to clear the interview

**Comment by RahulSurana123** [comment]
I am closing the issue let me know if you need nay other help
